const CONFIG = {
  GOOGLE_KEY: process.env.REACT_APP_GOOGLE_KEY || "PASTE_YOUR_GOOGLE_KEY_HERE",
  ANTHROPIC_KEY: process.env.REACT_APP_ANTHROPIC_KEY || "PASTE_YOUR_ANTHROPIC_KEY_HERE",
};

export default CONFIG;