const CONFIG = {
  GOOGLE_KEY: process.env.REACT_APP_GOOGLE_KEY || "PASTE_YOUR_GOOGLE_KEY_HERE",
  GEMINI_KEY: process.env.REACT_APP_ANTHROPIC_KEY || "AIzaSyDjRsKFld1_EtVFnYZuH9eDtD19jtbLCHA",
};

export default CONFIG;