const CONFIG = {
  GOOGLE_KEY: process.env.REACT_APP_GOOGLE_KEY || "PASTE_YOUR_GOOGLE_KEY_HERE",
  GEMINI_KEY: process.env.REACT_APP_GEMINI_KEY || "PASTE_YOUR_GEMINI_KEY_HERE",
};
export default CONFIG;